### ISSUE TITLE
Nothing happenfs after shareberry configuration

### ISSUE THREAD

**Issue by hollmanenciso** [raveberry/shareberry#1]
Hi, I just installed raveberry and also shareberry on my android (pixel 2xl)
but The shareberry don't perform anything after I configure the endpoint of my raveberry server (http://ip:8080).

**Comment by raveberry** [comment]
Oh, you're right. I recently changed the Interface on the Raveberry side but forgot to adapt Shareberry's call. Should be an easy fix though.

**Comment by raveberry** [comment]
Should be fixed with Raveberry version 0.5.2.
I also updated the default configuration of Shareberry to use the new development server port 8080.

**Comment by hollmanenciso** [comment]
Hi @raveberry I upgrade to 0.5.2
```
pi@raveberry:~ $ raveberry --version
0.5.2
```
but nothing happens on shareberry. just ask me for the endpoint of my pi and that's it.
On the other hand, after the upgrade, I'm getting this messages/errors:

```
pi@raveberry:~ $ raveberry run
This is the basic raveberry version using a debug server.
To install with all features run `raveberry system-install`
Watching for file changes with StatReloader
Performing system checks...

Cannot open /dev/spidev0.0. spi_bcm2835 module not loaded?
System check identified no issues (0 silenced).
May 03, 2020 - 18:42:22
Django version 2.2.10, using settings 'main.settings'
Starting ASGI/Channels version 2.4.0 development server at http://0:8080/
Quit the server with CONTROL-C.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/raveberry/core/util.py", line 16, in run_and_close_connection
    function(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/raveberry/core/musiq/player.py", line 281, in _loop
    self.queue.enqueue(song_provider.get_metadata(), False)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/raveberry/core/musiq/song_queue.py", line 29, in enqueue
    internal_url=metadata["internal_url"],
KeyError: 'internal_url'
```

**Comment by raveberry** [comment]
I think that these are two separate issues.
1. Shareberry
If you open the app, configuring the Raveberry endpoint is the only thing you can do there. The app becomes active when sharing a song or video. Shareberry then tries out all given endpoints in the specified order.
2. Raveberry
I'm not sure what the reason for this error message is. It seems to occur during repeating of the current song. If you did not yet collect a lot of data in your database, you could delete it by running `rm /home/pi/.local/lib/python3.7/site-packages/raveberry/db.sqlite3`. This _should_ fix the issue. If you want to keep the database or the problem persists, I would ask you to open an issue at Raveberry's repo so we can discuss this further.

**Comment by raveberry** [comment]
Closing due to inactivity.
Feel free to reopen if you encounter the issue again.
